
--q1. what is total revenue generated by male vs female ?
select gender ,
    sum(purchase_amount) as revenue 
from customer
group by gender;

--q2. which customer used a discount but still spent more than average purchase amount
select customer_id,
    purchase_amount
from customer
where discount_applied='yes' and purchase_amount>=
    (select avg(purchase_amount) from customer);

--q3 which are the top 5 products with highest average review rating?
select top 5  item_purchased,
    round(avg(review_Rating),2) as average_product_rating
from customer
group by item_purchased
order by average_product_rating desc;

--Q4 compare average  purchae amounts between standard and express shipping
select shipping_type,
    AVG(purchase_amount) as purchase_amount
from customer
where shipping_type in ('Standard','Express')
group by shipping_type;

--Q5 do subscribed customer spend more ?compare average spend 
	-- and total revenue between subscribers non subscribers 
select [subscription_status],
	count(customer_id) as total_customer,
	round(avg(purchase_amount),2) as average_spend,
	round(sum(purchase_amount),2) as total_revenue
from customer
group by subscription_status	
order by total_revenue,average_spend;

-- Q6 which 5 products have the highest percentage of purchase with discounts applied?
SELECT TOP 5 
    item_purchased,
   FORMAT( ROUND(
        (CAST(SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) AS DECIMAL(10,2)) 
        / COUNT(*) * 100), 
    2),'#.00') AS discount_rate
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate;


-- q7. segement customer into new ,returning and loyal based
   -- on their total numbers of previouse purchases and show the count of each segement
with customer_type as 
(
select customer_id,previous_purchases,
    case when previous_purchases=1 then 'New'
        when previous_purchases between 2 and  10 then 'returning'
        else   'Loyal' end as customer_segement
 from customer)
 select customer_segement,
    count(*) as number_of_customer
 from customer_type
 group by customer_segement
 order by number_of_customer desc

 -- Q8 what are the top 3 most purchased products withing each category 
 with item_cout as(
 select category,
    item_purchased,
    count(customer_id) as total_orders,
    row_number() over(partition by category order by count(customer_id) desc) as item_rank
 from customer
 group by category,item_purchased )
 select  item_rank,
    category,item_purchased,
    total_orders
 from item_cout
 where item_rank<=3;

 -- Q9  are the customers are repeat buyers(more than 5 previouse purchase ) also likely to subscribe
 select subscription_status,
    count(customer_id) as repeate_buyers
 from customer
 where previous_purchases>5
 group by subscription_status

 --q10  what is the revenue contribution of each age group?
 select age_group, 
    sum(purchase_amount) as total_revenue
 from customer
 group by age_group
 order  by total_revenue
 
 
 --q11. What are the top 3 locations with the highest sales performance?
  select top 5  location, 
    sum(purchase_amount) as total_revenue
 from customer
 group by location
 order  by total_revenue desc
